//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnAnimals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Article_ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> Date_Published { get; set; }
        public Nullable<int> Animal_ID { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
