//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnAnimals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Comment_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Animal_ID { get; set; }
        public string Comment_Text { get; set; }
        public Nullable<System.DateTime> Date_Posted { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
